### ISSUE TITLE
2d Homogeneous Rotation seems incorrect

### ISSUE THREAD

**Issue by aztecrex** [fu5ha/ultraviolet#143]
`Mat3::from_rotation_homogeneous(t)` seems to be giving me the wrong matrix.

for c = cos(t), s = sin(t), I expect **[[c,s,0],[-s,c,0],[0,0,1]]** but I get **[[c,s,0],[_s_,_-c_,0],[0,0,1]]** .

Maybe there is some model in play that I don't recognize.

version is 0.9

**Comment by fu5ha** [comment]
Here's the relevant code if you'd like to make a PR, probably just a typo that never got tested https://github.com/fu5ha/ultraviolet/blob/main/src/mat.rs#L393-L403

**Comment by aztecrex** [comment]
PR submitted
