### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by G0BL1N** [fu5ha/ultraviolet#154]
While working on the project, I noticed it doesn't have a license. Would you consider adding a license so people can know that they can use ultraviolet?
I would PR it too, but I don't know if you would want MIT or GNU GPL, or something else.

**Comment by fu5ha** [comment]
Ah, I do specify the licenses here https://github.com/fu5ha/ultraviolet/blob/main/Cargo.toml#L10 but should include the license texts in the repo as well probably.

**Comment by G0BL1N** [comment]
Or, right, I didn't notice it, sorry. Thanks for the reply. License is specified, so it's fine by me.

**Comment by safasofuoglu** [comment]
> Ah, I do specify the licenses here https://github.com/fu5ha/ultraviolet/blob/main/Cargo.toml#L10 but should include the license texts in the repo as well probably.

I believe this is still relevant, it took me a while to arrive here. Thanks!

**Comment by G0BL1N** [comment]
I guess I shouldn't have closed the issue this soon, even if I was satisfied with response. I'll reopen it (as it's still relevant), until the license file is added to the repo.

**Comment by acpiccolo** [comment]
Hi there! I wanted to check in on this issue. 

Since the `Cargo.toml` lists `MIT OR Apache-2.0 OR Zlib`, having the corresponding license files in the root folder would help downstream users and corporate compliance tools tremendously. 

Thanks for maintaining this awesome library!
