### ISSUE TITLE
Mat4::from_euler_angles appears to be producing incorrect rotations

### ISSUE THREAD

**Issue by alexgladd** [fu5ha/ultraviolet#155]
As referenced [here](https://github.com/fu5ha/ultraviolet/issues/130#issuecomment-1186973921) in #130, `Mat4::from_euler_angles(roll, pitch, yaw)` appears to actually be implementing `Mat4::from_euler_angles(pitch, yaw, roll)`.

I'm seeing this same issue in something I'm working on where I'm using `Mat4::from_euler_angles` to build a rotation matrix as part of a larger computation for a camera view projection matrix. If I do a "roll", the scene appears as if the camera were pitched. If I do a "pitch", the scene appears as if the camera were yawed. If I do a "yaw" the scene appears as if the camera were rolled.

I'm calculating the VP matrix like:

```rust
// roll, pitch, and yaw are provided as radians
let transform = Mat4::from_translation(self.position) * Mat4::from_euler_angles(roll, pitch, yaw);
// invert the transform to get a camera view matrix
let view = transform.inversed();
// add the projection to get a camera view projection matrix, where projection is created
// using ultraviolet::projection::orthographic_wgpu_dx
let view_projection = projection * view;
```

Am I doing something wrong or is this a bug?

Note that if I use the individual rotations like `Mat4f::from_rotation_z(roll)` I get the expected results.

**Comment by fu5ha** [comment]
Sounds like it is indeed a bug :)
