### ISSUE TITLE
Quaternions

### ISSUE THREAD

**Issue by SylvanSerenity** [fu5ha/ultraviolet#170]
This may be controversial, but hear me out! I have been considering adding Quaternion types for the various reasons.

### Pros
* Constructing quaternions from axis-angle representation is much more intuitive since quaternions can represent a rotation around an axis directly, whereas rotors use bivectors.
* Unlike rotors, a rotation about each axis is **always counterclockwise** from the vector's origin. Rotors rotate counterclockwise around the x and z axes but clockwise around the y axis in my testing. Looking at `Rotor3::from_quaternion_array`, they indeed are stored in the order `w, [-z, y, -x]`.
  * As far as I am aware, to do a simple yaw adjustment using rotors, you need to find the local x and z axes (`rotor * axis`), get the wedge product of those two vectors for the plane, then use `Rotor3::from_angle_plane` to get the Rotor because you cannot rotate a Bivec3:
    ```Rust
    fn yaw(left_by_radians: f32, rotor: Rotor3) -> Rotor3 {
        let x_axis = rotor * Vec3::unit_x();
        let z_axis = rotor * Vec3::unit_z();
        let vertical_plane = x_axis.wedge(z_axis()); // xz plane
        let r = Rotor3::rotor3_from_angle_plane(left_by_radians, vertical_plane);
        r * rotor
    }
    ```
  * For quaternions, only the following is needed:
    ```Rust
    fn yaw(right_by_radians: f32, rotor: Rotor3) -> Rotor3 {
        let vertical_axis = rotor * Vec3::unit_y(); // y-axis
        let r = Rotor3::rotor3_from_angle_plane(right_by_radians, vertical_axis);
        r * rotor
    }
    ```
* Similar to rotors, they do not suffer from gimbal lock, they are great with slerp, and almost all of the math is the same.

### Cons
* **ultraviolet** fans seem to have a disdain for quaternions due to them being difficult to understand and less intuitive than rotors.
* As mentioned in the [Rotor](https://docs.rs/ultraviolet/latest/ultraviolet/rotor/index.html) documentation, they only work in 3D space, whereas rotors work in higher and lower dimensions. I believe a significant amount of games are 3D to justify implementing quaternions.

### Abstraction
To address complexity, functions to find axes could be abstracted to make using them as easy as possible:
* Axis-angle representation: `Quat::from_axis_angle(axis: Vec3, angle: f32)`
* Local axis extraction: `Quat::y_axis(self)` with alias `Quat::vertical_axis(self)`
* Local Euler rotations: `Quat::yaw(&mut self, right_by_angle: f32)`

### Conclusion
I believe that quaternions are used for 3D applications and can be made very intuitive with some abstraction, especially since they can be more easily thought of as axis-angle representation which (at least to me) is more intuitive than planar representation. It also helps with visualizing other operations like slerp when thought of that way.

However, I may be biased since I have not used rotors much and was a bit disappointed with the steps required to implement rotors for representing a camera rotation compared to what is required using quaternions. After some thinking, I do think rotors are best for 2D and any dimensions higher than 3D, but it seems more performant and simple to use quaternions for 3D space in my opinion. At the very least it could provide an option for users who prefer quaternions.

Let me know what you think and if I should consider implementing it!

**Comment by fu5ha** [comment]
A quaternion is just one formulation of the more general term, which is rotor. Anything you can do with one you can also do with the other. The clockwise/anticlockwiseness of the positive rotation in each axis is just a matter of a plus or minus sign. Indeed though the thing you mention is one of the reasons that rotors are most commonly formulated with the `xz` bivector being inversed as `zx` in the literature -- https://github.com/fu5ha/ultraviolet/pull/131 makes this change, and it's one I've been meaning to just land for a while but haven't had a real reason to.

As far as I can tell what you mean by a yaw transformation (neither of your snippets actually work, as `r` is not defined at the start..?), you can do this more simply in either case..

```rust
fn yaw(right_by_radians: f32, rotor: Rotor3) -> Rotor3 {
    let vertical_plane = -Bivec3::unit_xz(); // y-axis
    let yaw = Rotor3::from_angle_plane(right_by_radians, vertical_plane);
    yaw * rotor
}
```
If you want the rotation to be in the "local" space then replace the last line with `rotor * yaw`. Note I just invert the unit xz bivector (which is the same thing you'd get by wedging Z axis with X axis).

**Comment by SylvanSerenity** [comment]
I left some artifacts of previous code that I had forgotten to remove in my example, sorry! I made a quick edit to fix it. Can't believe I didn't notice that before posting🤦

The issue was just me having a fundamental misunderstanding of how rotations can be applied. I wrote a test for the variation you suggested against what I had originally, and sure enough the resulting rotor is equivalent!

```Rust
#[test]
fn rotation_test() {
    // Start with an ambiguous rotation to skew the local up axes away from the global axes
    let start_orientation = Rotor3::from_euler_angles(
        std::f32::consts::FRAC_PI_6,
        std::f32::consts::FRAC_PI_2,
        std::f32::consts::FRAC_PI_8,
    );

    // Rotate around "local up plane" and apply to "global up plane" (your suggested variation)
    let a_vertical_plane = -Bivec3::unit_xz();
    let a_yaw = Rotor3::from_angle_plane(std::f32::consts::FRAC_PI_2, a_vertical_plane);
    let a_rotated = start_orientation * a_yaw;

    // Rotate "global up plane", then apply current rotation (my original implementation)
    let local_x = start_orientation * Vec3::unit_x();
    let local_z = start_orientation * Vec3::unit_z();
    let b_vertical_plane = local_z.wedge(local_x);
    let b_yaw = Rotor3::from_angle_plane(std::f32::consts::FRAC_PI_2, b_vertical_plane);
    let b_rotated = b_yaw * start_orientation;
    println!("{:?}\n{:?}", a_rotated, b_rotated);
    assert!(
            (a_rotated.s - b_rotated.s).abs() <= 0.0001
            (a_rotated.bv.xz - b_rotated.bv.xz).abs() <= 0.0001
            (a_rotated.bv.xy - b_rotated.bv.xy).abs() <= 0.0001
            (a_rotated.bv.yz - b_rotated.bv.yz).abs() <= 0.0001
        );
}
```

I apologize for the confusion, and I now see why and how rotors are used and agree that you aren't missing out by not using quaternions. I'll check out that issue about using zx instead of xz as well. Thank you!

**Comment by fu5ha** [comment]
No worries, this stuff can be a lot to wrap one's head around. The composition order changing the effect of application thing is a particularly important and useful one to keep in mind :) it applies to rotation matrices etc as well

**Comment by fu5ha** [comment]
Oh, also, it should be possible to apply a rotor to a bivector (i.e. rotate it by the rotor). I just haven't implemented that yet as I haven't found a use for it that can't be just reformulated slightly. You could open an issue for that if you want.
