### ISSUE TITLE
Rotor3 creates NaNs

### ISSUE THREAD

**Issue by joeftiger** [fu5ha/ultraviolet#93]
When trying to create a rotation of vector to its exact opposite direction, the rotor will be filled with NaNs. 

Reproducible code:

```rust
use ultraviolet::{Vec3, Rotor3};

fn main() {
    let from = Vec3::unit_x();
    let to = -from;

    let rotor = Rotor3::from_rotation_between(from, to);
    println!("{:?}", rotor);
}
```

This leads to unexpected behaviour down the road.

**Comment by joeftiger** [comment]
This happens due to `from.wedge(to) = Vec3::zero()`. Normalizing it leads to the NaNs. 
Either `Rotor3` needs to check against `Vec3::zero()`, or it should at least be explicitly stated in the documentation.

The latter approach does seem bad though, since one expects a perfectly fine rotation instead of undefined behaviour.

**Comment by joeftiger** [comment]
A fix for `Rotor3` is easy, but I am absolutely not familiar with simd units. Therefore a proposed fix would not benefit any `Rotor3x4` / `Rotor3x8`.

**Comment by thenlevy** [comment]
I think the result should be undefined when trying to compute a rotor from a rotation between two parallels vector. The problem is that the plane of the rotation is undefined in that case. 
For example, what should be the output of the this program ?
```rust
use ultraviolet::{Vec3, Rotor3};

fn main() {
    let from = Vec3::unit_x();
    let to = -from;

    let rotor = Rotor3::from_rotation_between(from, to);
    println!("{:?}", Vec3::unit_y().rotated_by(rotor));
    println!("{:?}", Vec3::unit_z().rotated_by(rotor));
}
```
If a rotor transform x in -x, y in -y and z in -z then it does not represents a rotation anymore

**Comment by joeftiger** [comment]
> If a rotor transform x in -x, y in -y and z in -z then it does not represents a rotation anymore
For me it's still a rotation by 180°, even if a specific plane of rotation cannot be given. 
One could create a plane by taking any arbitrary vector and using the wedge product as the plane normal.

**Comment by thenlevy** [comment]
> For me it's still a rotation by 180°, even if a specific plane of rotation cannot be given.

A rotation is a linear transformation that is orthogonal and has determinant 1. In 3D, the linear transform x -> -x has determinant -1 so it is not a rotation.


> One could create a plane by taking any arbitrary vector and using the wedge product as the plane normal.

But then this piece of code
```rust
use ultraviolet::{Vec3, Rotor3};

fn main() {
    let from = Vec3::unit_x();
    let to = -from;

    let rotor = Rotor3::from_rotation_between(from, to);
    println!("{:?}", Vec3::unit_y().rotated_by(rotor));
    println!("{:?}", Vec3::unit_z().rotated_by(rotor));
}
```
Would have undefined behavior. 

In my opinion, the current behavior should be kept, but better documented.

**Comment by joeftiger** [comment]
I discussed this with someone more knowledgeable in computer graphics and we came to the conclusion that this should really be an `Option<Rotor*>` if it can be undefined. This would require a hard bump in versioning.

**Comment by termhn** [comment]
Eh, it's a bit of a philosophical issue. There are several operations which may fail in math if given invalid inputs, for example an inverse on a matrix might fail if the matrix is noninvertible. My stance to this point with `ultraviolet` is to just document what constitutes invalid input and say that if you give it invalid input then the resulting value may be nonsensical. There are tradeoffs to both methods, but generally, with my philosophy towards a math library for games/graphics, I think that I want to keep it the way it is right now: it places onus on the user to validate their own inputs if they believe they might be invalid, but it prevents us from forcing everyone to always check if the result is valid, even if they have outside information that it will be.

**Comment by rlidwka** [comment]
> The problem is that the plane of the rotation is undefined in that case.

There are many possible planes of rotation. You can pick any.

`glam` has [three methods](https://docs.rs/glam/latest/glam/f32/struct.Vec3.html#method.normalize) for vector normalization:
 - `fn normalize(self) -> Self`
 - `fn try_normalize(self) -> Option<Self>`
 - `fn normalize_or_zero(self) -> Self`

First is used if you know input is valid. Second is used when you don't. Third is used if you want a reasonable fallback.

Can we have something similar? One method that returns NaN, one method that returns an Option, and one method that always produces a valid Rotor (which deterministically picks *some* plane for antiparallel vectors, identity rotor if any vector is zero, etc.)?
